# Python Equivalent Code for Chapter 2 of ISLR

Here I try to map the commands specified in R to 
the python equivalent. All commands are as mentioned
in ISLR chapter 2.

In [1]:
# Basic Commands
# creating a vector (python equivalent is list)
x=[1,2,3,4]   
y = [1,4,3,7]
type(x)

list

In [2]:
# Finding the length
# R command : length (x)
len(x)

4

In [3]:
# adding two lists
# R command: x+y
# In python plain x+y will concatenate the two lists. 
# So numpy arrays make it easier. 

import numpy as np
np.array(x) + np.array(y)

array([ 2,  6,  6, 11])

In [5]:
# Creating a matrix
# R command : x=matrix (data=c(1,2,3,4) , nrow=2, ncol =2)
# R reads this data column wise so we need to specify the order explicitly
x_2 = np.array([1,2,3,4]).reshape((2,2),order="F") 
print(x_2)

[[1 3]
 [2 4]]


In [6]:
# matrix (c(1,2,3,4) ,2,2,byrow =TRUE)
np.array([1,2,3,4]).reshape((2,2)) 

array([[1, 2],
       [3, 4]])

In [7]:
# R  command : sqrt(x)
# R command : x^2
np.sqrt(x)
np.sqrt(x_2)
np.square(x_2)

array([[ 1,  9],
       [ 4, 16]], dtype=int32)

In [8]:
# R command:  rnorm(50)
np.random.randn(50)

array([-0.25827447,  1.06218585, -1.09497862,  0.84604725, -0.09861192,
       -2.22038924, -0.27290557,  0.34115063, -1.1178686 , -0.26257729,
       -0.76987718, -2.33235329,  0.92735639,  0.74527308, -0.20165203,
        0.05101061,  0.49166043, -0.39073755,  0.64280314, -0.11251166,
       -0.36843931, -0.52712183, -0.58745556,  1.78057029,  0.09575703,
        2.59059413,  0.91236506,  2.46725447, -1.00329635, -1.43487068,
        0.65816094,  1.66367887,  0.04142814, -1.35169134, -0.07488342,
        0.39946233,  0.73228718, -1.69187921,  0.52406355, -1.26738265,
       -1.69894855,  0.35202011,  1.65845467, -1.32382478, -0.79673535,
        0.45899258,  2.10917165,  0.95584701, -0.03726276,  0.1682482 ])

In [9]:
# R command :  y= x + rnorm(50, mean = 50, sd= 0.1)
# cor(x,y)
x= np.random.randn(50)
y= x + (0.1*np.random.randn(50) + 50)
np.corrcoef(y,x)

array([[ 1.        ,  0.99416617],
       [ 0.99416617,  1.        ]])

### Graphics (will update soon)

In [10]:

# x= rnorm(100)
# y= rnorm(100)
# plot (x, y)
# plot(x,y,xlab=" this is the x-axis",ylab=" this is the y-axis",
#        main=" Plot of X vs Y")

import matplotlib.pyplot as plt

x = np.random.randn(50)
y = np.random.randn(50)
plt.scatter(x,y)

### Indexing Data

In [11]:
# A=matrix (1:16 ,4 ,4)
# A[2,3]

A = np.array([list(range(1,17))]).reshape((4,4), order="F") # gotta give last number +1
A[1,2] # python indexing starts from 0


10

In [12]:
# A[c(1,3) ,c(2,4) ]
# A[-c(1,3),]
A[np.ix_([0,2],[1,3])]
A[np.ix_(range(3),range(1,4))]
np.delete(A, [0,2], axis=0)

array([[ 2,  6, 10, 14],
       [ 4,  8, 12, 16]])